-- =====================================================================================
-- SQL MAESTRO - COTIZADOR (Esquema: finanzas)
-- Compatible con Supabase (PostgreSQL) | Ejecutar en: Supabase Studio -> SQL Editor
-- =====================================================================================

-- Extensiones necesarias (para gen_random_uuid)
create extension if not exists pgcrypto;

-- 1) Esquema
create schema if not exists finanzas;

-- 2) Tabla: espacios
create table if not exists finanzas.espacios (
  id              bigint generated by default as identity primary key,
  created_at      timestamptz not null default timezone('utc'::text, now()),
  clave           text not null,
  nombre          text not null,
  tipo            text not null,
  descripcion     text,
  requisitos      text,
  imagen_url      text,
  activo          boolean default true,
  precio_base     numeric default 0,
  ajuste_tipo     text default 'ninguno',
  ajuste_porcentaje integer default 0,
  activa          boolean default true,
  impuestos_ids   jsonb default '[]'::jsonb,
  color           varchar default '#374151'
);

create unique index if not exists espacios_clave_uq on finanzas.espacios (clave);

-- 3) Tabla: conceptos_catalogo
create table if not exists finanzas.conceptos_catalogo (
  id              bigint generated by default as identity primary key,
  nombre          text not null,
  precio_sugerido numeric default 0,
  activo          boolean default true,
  created_at      timestamptz default now()
);

-- 4) Tabla: impuestos
create table if not exists finanzas.impuestos (
  id                bigint generated by default as identity primary key,
  nombre            text not null,
  porcentaje        numeric not null,
  activo            boolean default true,
  created_at        timestamptz not null default timezone('utc'::text, now()),
  impuestos_aplicados jsonb
);

-- 5) Tabla: cotizaciones
create table if not exists finanzas.cotizaciones (
  id                  uuid primary key default gen_random_uuid(),
  created_at           timestamptz not null default timezone('utc'::text, now()),
  creado_por           uuid,
  espacio_id           bigint,
  espacio_nombre       text,
  espacio_clave        text,
  cliente_nombre       text,
  cliente_rfc          text,
  cliente_contacto     text,
  cliente_email        text,
  cliente_telefono     text,
  fecha_inicio         date not null,
  fecha_fin            date not null,
  precio_final         numeric not null,
  desglose_precios     jsonb,
  status               text default 'aprobada',
  numero_orden         text,
  numero_contrato      text,
  factura_pdf_url      text,
  factura_xml_url      text,
  contrato_url         text,
  url_cotizacion_final text,
  url_orden_compra     text,
  fecha_orden_compra   timestamptz,
  datos_fiscales       jsonb default '{}'::jsonb,
  datos_factura        jsonb default '{}'::jsonb,
  conceptos_adicionales jsonb default '[]'::jsonb,
  tipo_ajuste          text default 'ninguno',
  valor_ajuste         numeric default 0,
  ajuste_es_porcentaje boolean default false,
  desglose_impuestos   jsonb default '[]'::jsonb,
  historial_pagos      jsonb default '[]'::jsonb
);

alter table finanzas.cotizaciones
  drop constraint if exists cotizaciones_espacio_id_fkey;

alter table finanzas.cotizaciones
  add constraint cotizaciones_espacio_id_fkey
  foreign key (espacio_id) references finanzas.espacios(id);

create index if not exists cotizaciones_created_at_idx on finanzas.cotizaciones(created_at desc);
create index if not exists cotizaciones_status_idx on finanzas.cotizaciones(status);

-- =====================================================================================
-- PERFIL / AUTH COMPATIBLE (para que el frontend no falle con perfiles/roles)
-- =====================================================================================

-- Tabla profiles en public (patrón típico de Supabase)
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text,
  role text default 'admin',
  app_metadata jsonb default '{}'::jsonb,
  created_at timestamptz default timezone('utc'::text, now())
);

alter table public.profiles enable row level security;

drop policy if exists "Profiles are readable by authenticated users" on public.profiles;
create policy "Profiles are readable by authenticated users"
  on public.profiles for select
  to authenticated
  using (true);

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
  on public.profiles for update
  to authenticated
  using (auth.uid() = id);

-- Trigger: insertar profile al crear usuario en auth.users
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
as $$
begin
  insert into public.profiles (id, username, role)
  values (new.id, coalesce(new.raw_user_meta_data->>'username', split_part(new.email,'@',1)), 'admin')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- =====================================================================================
-- RLS (Row Level Security) para finanzas: acceso completo a usuarios autenticados
-- =====================================================================================

alter table finanzas.espacios enable row level security;
alter table finanzas.conceptos_catalogo enable row level security;
alter table finanzas.impuestos enable row level security;
alter table finanzas.cotizaciones enable row level security;

-- ESPACIOS
drop policy if exists "fin_espacios_all_auth" on finanzas.espacios;
create policy "fin_espacios_all_auth"
  on finanzas.espacios for all
  to authenticated
  using (true)
  with check (true);

-- CONCEPTOS
drop policy if exists "fin_conceptos_all_auth" on finanzas.conceptos_catalogo;
create policy "fin_conceptos_all_auth"
  on finanzas.conceptos_catalogo for all
  to authenticated
  using (true)
  with check (true);

-- IMPUESTOS
drop policy if exists "fin_impuestos_all_auth" on finanzas.impuestos;
create policy "fin_impuestos_all_auth"
  on finanzas.impuestos for all
  to authenticated
  using (true)
  with check (true);

-- COTIZACIONES
drop policy if exists "fin_cotizaciones_all_auth" on finanzas.cotizaciones;
create policy "fin_cotizaciones_all_auth"
  on finanzas.cotizaciones for all
  to authenticated
  using (true)
  with check (true);

-- =====================================================================================
-- STORAGE (opcional): bucket 'espacios' público para logo.png
-- =====================================================================================
-- Si vas a usar el logo desde Storage local, descomenta:
-- insert into storage.buckets (id, name, public)
-- values ('espacios', 'espacios', true)
-- on conflict (id) do update set public = true;
