create schema if not exists "finanzas";

create schema if not exists "finanzas_casadepiedra";


  create table "finanzas"."clientes" (
    "id" uuid not null default gen_random_uuid(),
    "nombre_completo" text not null,
    "telefono" text,
    "correo" text,
    "rfc" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );


alter table "finanzas"."clientes" enable row level security;


  create table "finanzas"."conceptos_catalogo" (
    "id" bigint generated by default as identity not null,
    "nombre" text not null,
    "precio_sugerido" numeric default 0,
    "activo" boolean default true,
    "created_at" timestamp with time zone default now()
      );


alter table "finanzas"."conceptos_catalogo" enable row level security;


  create table "finanzas"."cotizaciones" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "creado_por" uuid,
    "espacio_id" bigint,
    "espacio_nombre" text,
    "espacio_clave" text,
    "cliente_nombre" text,
    "cliente_rfc" text,
    "cliente_contacto" text,
    "cliente_email" text,
    "cliente_telefono" text,
    "fecha_inicio" date not null,
    "fecha_fin" date not null,
    "precio_final" numeric not null,
    "desglose_precios" jsonb,
    "status" text default 'aprobada'::text,
    "numero_orden" text,
    "numero_contrato" text,
    "factura_pdf_url" text,
    "factura_xml_url" text,
    "contrato_url" text,
    "url_cotizacion_final" text,
    "url_orden_compra" text,
    "fecha_orden_compra" timestamp with time zone,
    "datos_fiscales" jsonb default '{}'::jsonb,
    "conceptos_adicionales" jsonb default '[]'::jsonb,
    "tipo_ajuste" text default 'ninguno'::text,
    "valor_ajuste" numeric default 0,
    "ajuste_es_porcentaje" boolean default false,
    "desglose_impuestos" jsonb default '[]'::jsonb,
    "historial_pagos" jsonb default '[]'::jsonb,
    "datos_factura" jsonb default '{}'::jsonb,
    "cliente_id" uuid
      );


alter table "finanzas"."cotizaciones" enable row level security;


  create table "finanzas"."espacios" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "clave" text not null,
    "nombre" text not null,
    "tipo" text not null,
    "descripcion" text,
    "requisitos" text,
    "imagen_url" text,
    "activo" boolean default true,
    "precio_base" numeric default 0,
    "ajuste_tipo" text default 'ninguno'::text,
    "ajuste_porcentaje" integer default 0,
    "activa" boolean default true,
    "impuestos_ids" jsonb default '[]'::jsonb,
    "color" character varying default '#374151'::character varying
      );


alter table "finanzas"."espacios" enable row level security;


  create table "finanzas"."impuestos" (
    "id" bigint generated by default as identity not null,
    "nombre" text not null,
    "porcentaje" numeric not null,
    "activo" boolean default true,
    "created_at" timestamp with time zone default timezone('utc'::text, now()),
    "impuestos_aplicados" jsonb
      );


alter table "finanzas"."impuestos" enable row level security;


  create table "finanzas_casadepiedra"."clientes" (
    "id" uuid not null default gen_random_uuid(),
    "nombre_completo" text not null,
    "telefono" text,
    "correo" text,
    "rfc" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );


alter table "finanzas_casadepiedra"."clientes" enable row level security;


  create table "finanzas_casadepiedra"."conceptos_catalogo" (
    "id" bigint generated by default as identity not null,
    "nombre" text not null,
    "precio_sugerido" numeric default 0,
    "activo" boolean default true,
    "created_at" timestamp with time zone default now()
      );


alter table "finanzas_casadepiedra"."conceptos_catalogo" enable row level security;


  create table "finanzas_casadepiedra"."cotizaciones" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "creado_por" uuid,
    "espacio_id" bigint,
    "espacio_nombre" text,
    "espacio_clave" text,
    "cliente_nombre" text,
    "cliente_rfc" text,
    "cliente_contacto" text,
    "cliente_email" text,
    "cliente_telefono" text,
    "fecha_inicio" date not null,
    "fecha_fin" date not null,
    "precio_final" numeric not null,
    "desglose_precios" jsonb,
    "status" text default 'aprobada'::text,
    "numero_orden" text,
    "numero_contrato" text,
    "factura_pdf_url" text,
    "factura_xml_url" text,
    "contrato_url" text,
    "url_cotizacion_final" text,
    "url_orden_compra" text,
    "fecha_orden_compra" timestamp with time zone,
    "datos_fiscales" jsonb default '{}'::jsonb,
    "conceptos_adicionales" jsonb default '[]'::jsonb,
    "tipo_ajuste" text default 'ninguno'::text,
    "valor_ajuste" numeric default 0,
    "ajuste_es_porcentaje" boolean default false,
    "desglose_impuestos" jsonb default '[]'::jsonb,
    "historial_pagos" jsonb default '[]'::jsonb,
    "datos_factura" jsonb default '{}'::jsonb,
    "cliente_id" uuid,
    "personas" integer default 0
      );


alter table "finanzas_casadepiedra"."cotizaciones" enable row level security;


  create table "finanzas_casadepiedra"."espacios" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "clave" text not null,
    "nombre" text not null,
    "tipo" text not null,
    "descripcion" text,
    "requisitos" text,
    "imagen_url" text,
    "activo" boolean default true,
    "precio_base" numeric default 0,
    "ajuste_tipo" text default 'ninguno'::text,
    "ajuste_porcentaje" integer default 0,
    "activa" boolean default true,
    "impuestos_ids" jsonb default '[]'::jsonb,
    "color" character varying default '#374151'::character varying,
    "precios_por_dia" jsonb default '{"lunes": 0, "jueves": 0, "martes": 0, "sabado": 0, "domingo": 0, "viernes": 0, "miercoles": 0}'::jsonb
      );


alter table "finanzas_casadepiedra"."espacios" enable row level security;


  create table "finanzas_casadepiedra"."impuestos" (
    "id" bigint generated by default as identity not null,
    "nombre" text not null,
    "porcentaje" numeric not null,
    "activo" boolean default true,
    "created_at" timestamp with time zone default timezone('utc'::text, now()),
    "impuestos_aplicados" jsonb
      );


alter table "finanzas_casadepiedra"."impuestos" enable row level security;


  create table "public"."profiles" (
    "id" uuid not null,
    "email" text,
    "username" text,
    "role" text not null default 'user'::text,
    "tenant" text not null default 'plaza_mayor'::text,
    "app_metadata" jsonb not null default '{}'::jsonb,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "allowed_tenants" text[] not null default ARRAY['plaza_mayor'::text]
      );


alter table "public"."profiles" enable row level security;

CREATE UNIQUE INDEX clientes_pkey ON finanzas.clientes USING btree (id);

CREATE UNIQUE INDEX conceptos_catalogo_pkey ON finanzas.conceptos_catalogo USING btree (id);

CREATE UNIQUE INDEX cotizaciones_pkey ON finanzas.cotizaciones USING btree (id);

CREATE UNIQUE INDEX espacios_pkey ON finanzas.espacios USING btree (id);

CREATE INDEX idx_finanzas_clientes_correo ON finanzas.clientes USING btree (lower(correo));

CREATE INDEX idx_finanzas_clientes_nombre ON finanzas.clientes USING btree (lower(nombre_completo));

CREATE INDEX idx_finanzas_clientes_rfc ON finanzas.clientes USING btree (rfc);

CREATE INDEX idx_finanzas_cotizaciones_cliente_id ON finanzas.cotizaciones USING btree (cliente_id);

CREATE UNIQUE INDEX impuestos_pkey ON finanzas.impuestos USING btree (id);

CREATE UNIQUE INDEX clientes_pkey ON finanzas_casadepiedra.clientes USING btree (id);

CREATE UNIQUE INDEX conceptos_catalogo_pkey ON finanzas_casadepiedra.conceptos_catalogo USING btree (id);

CREATE UNIQUE INDEX cotizaciones_pkey ON finanzas_casadepiedra.cotizaciones USING btree (id);

CREATE UNIQUE INDEX espacios_pkey ON finanzas_casadepiedra.espacios USING btree (id);

CREATE INDEX idx_fcdp_clientes_correo ON finanzas_casadepiedra.clientes USING btree (lower(correo));

CREATE INDEX idx_fcdp_clientes_nombre ON finanzas_casadepiedra.clientes USING btree (lower(nombre_completo));

CREATE INDEX idx_fcdp_clientes_rfc ON finanzas_casadepiedra.clientes USING btree (rfc);

CREATE INDEX idx_fcdp_cotizaciones_cliente_id ON finanzas_casadepiedra.cotizaciones USING btree (cliente_id);

CREATE UNIQUE INDEX impuestos_pkey ON finanzas_casadepiedra.impuestos USING btree (id);

CREATE INDEX profiles_allowed_tenants_gin ON public.profiles USING gin (allowed_tenants);

CREATE INDEX profiles_email_idx ON public.profiles USING btree (lower(email));

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE INDEX profiles_tenant_idx ON public.profiles USING btree (tenant);

alter table "finanzas"."clientes" add constraint "clientes_pkey" PRIMARY KEY using index "clientes_pkey";

alter table "finanzas"."conceptos_catalogo" add constraint "conceptos_catalogo_pkey" PRIMARY KEY using index "conceptos_catalogo_pkey";

alter table "finanzas"."cotizaciones" add constraint "cotizaciones_pkey" PRIMARY KEY using index "cotizaciones_pkey";

alter table "finanzas"."espacios" add constraint "espacios_pkey" PRIMARY KEY using index "espacios_pkey";

alter table "finanzas"."impuestos" add constraint "impuestos_pkey" PRIMARY KEY using index "impuestos_pkey";

alter table "finanzas_casadepiedra"."clientes" add constraint "clientes_pkey" PRIMARY KEY using index "clientes_pkey";

alter table "finanzas_casadepiedra"."conceptos_catalogo" add constraint "conceptos_catalogo_pkey" PRIMARY KEY using index "conceptos_catalogo_pkey";

alter table "finanzas_casadepiedra"."cotizaciones" add constraint "cotizaciones_pkey" PRIMARY KEY using index "cotizaciones_pkey";

alter table "finanzas_casadepiedra"."espacios" add constraint "espacios_pkey" PRIMARY KEY using index "espacios_pkey";

alter table "finanzas_casadepiedra"."impuestos" add constraint "impuestos_pkey" PRIMARY KEY using index "impuestos_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "finanzas"."cotizaciones" add constraint "cotizaciones_cliente_id_fkey" FOREIGN KEY (cliente_id) REFERENCES finanzas.clientes(id) ON DELETE SET NULL not valid;

alter table "finanzas"."cotizaciones" validate constraint "cotizaciones_cliente_id_fkey";

alter table "finanzas"."cotizaciones" add constraint "fk_cotizaciones_espacios" FOREIGN KEY (espacio_id) REFERENCES finanzas.espacios(id) ON DELETE SET NULL not valid;

alter table "finanzas"."cotizaciones" validate constraint "fk_cotizaciones_espacios";

alter table "finanzas_casadepiedra"."cotizaciones" add constraint "cotizaciones_cliente_id_fkey" FOREIGN KEY (cliente_id) REFERENCES finanzas_casadepiedra.clientes(id) ON DELETE SET NULL not valid;

alter table "finanzas_casadepiedra"."cotizaciones" validate constraint "cotizaciones_cliente_id_fkey";

alter table "public"."profiles" add constraint "profiles_allowed_tenants_valid" CHECK ((allowed_tenants <@ ARRAY['plaza_mayor'::text, 'casa_de_piedra'::text])) not valid;

alter table "public"."profiles" validate constraint "profiles_allowed_tenants_valid";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.can_access_cp()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
 SET row_security TO 'off'
AS $function$
  SELECT
    public.profile_role_norm() IN ('admin','ambos','casa_de_piedra')
    OR public.profile_has_tenant_norm('casa_de_piedra');
$function$
;

CREATE OR REPLACE FUNCTION public.can_access_pm()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
 SET row_security TO 'off'
AS $function$
  SELECT
    public.profile_role_norm() IN ('admin','ambos','plaza_mayor')
    OR public.profile_has_tenant_norm('plaza_mayor');
$function$
;

CREATE OR REPLACE FUNCTION public.get_my_module_access()
 RETURNS jsonb
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select jsonb_build_object(
    'role', coalesce(p.role, 'user'),
    'allowed_tenants', coalesce(p.allowed_tenants, array[]::text[]),
    'show_plaza_mayor', (public.is_admin() or ('plaza_mayor' = any(coalesce(p.allowed_tenants, array[]::text[])))),
    'show_casa_de_piedra', (public.is_admin() or ('casa_de_piedra' = any(coalesce(p.allowed_tenants, array[]::text[]))))
  )
  from public.profiles p
  where p.id = auth.uid();
$function$
;

CREATE OR REPLACE FUNCTION public.get_my_role()
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'auth', 'extensions'
AS $function$
DECLARE
  current_role text;
BEGIN
  -- Obtenemos el rol directo del perfil
  SELECT role INTO current_role
  FROM public.profiles
  WHERE id = auth.uid();
  
  RETURN current_role;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into public.profiles (id, email, username, role, allowed_tenants, app_metadata)
  values (
    new.id,
    new.email,
    coalesce(split_part(new.email, '@', 1), 'Usuario'),
    'user',
    array['plaza_mayor']::text[],
    '{}'::jsonb
  )
  on conflict (id) do nothing;

  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user_profile()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'auth', 'extensions'
AS $function$
begin
  insert into public.profiles (id, username, role, app_metadata)
  values (new.id, split_part(new.email, '@', 1), 'admin', '{}'::jsonb)
  on conflict (id) do nothing;
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.has_tenant_access(tenant text)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT EXISTS (
    SELECT 1
    FROM public.profiles p
    WHERE p.id = auth.uid()
      AND (
        lower(coalesce(p.role,'')) = 'admin'
        OR lower(tenant) = ANY (SELECT lower(x) FROM unnest(coalesce(p.allowed_tenants,'{}'::text[])) x)
      )
  );
$function$
;

CREATE OR REPLACE FUNCTION public.is_admin()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
 SET row_security TO 'off'
AS $function$
  SELECT public.profile_role_norm() = 'admin';
$function$
;

CREATE OR REPLACE FUNCTION public.jwt_role()
 RETURNS text
 LANGUAGE sql
 STABLE
 SET search_path TO 'public', 'extensions'
AS $function$
  select nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'role';
$function$
;

CREATE OR REPLACE FUNCTION public.normalize_key(t text)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'public'
AS $function$
  SELECT trim(both '_' FROM regexp_replace(lower(coalesce(t,'')), '[^a-z0-9]+', '_', 'g'));
$function$
;

CREATE OR REPLACE FUNCTION public.profile_has_tenant_norm(tenant text)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
 SET row_security TO 'off'
AS $function$
  SELECT EXISTS (
    SELECT 1
    FROM public.profiles p
    WHERE p.id = auth.uid()
      AND public.normalize_key(tenant) = ANY (
        SELECT public.normalize_key(x) FROM unnest(coalesce(p.allowed_tenants,'{}'::text[])) x
      )
  );
$function$
;

CREATE OR REPLACE FUNCTION public.profile_role()
 RETURNS text
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
 SET row_security TO 'off'
AS $function$
  SELECT lower(coalesce(p.role,''))
  FROM public.profiles p
  WHERE p.id = auth.uid()
  LIMIT 1;
$function$
;

CREATE OR REPLACE FUNCTION public.profile_role_norm()
 RETURNS text
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
 SET row_security TO 'off'
AS $function$
  SELECT public.normalize_key(p.role)
  FROM public.profiles p
  WHERE p.id = auth.uid()
  LIMIT 1;
$function$
;

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
 RETURNS event_trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public', 'extensions'
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$
;

grant delete on table "finanzas"."clientes" to "anon";

grant insert on table "finanzas"."clientes" to "anon";

grant references on table "finanzas"."clientes" to "anon";

grant select on table "finanzas"."clientes" to "anon";

grant trigger on table "finanzas"."clientes" to "anon";

grant truncate on table "finanzas"."clientes" to "anon";

grant update on table "finanzas"."clientes" to "anon";

grant delete on table "finanzas"."clientes" to "authenticated";

grant insert on table "finanzas"."clientes" to "authenticated";

grant references on table "finanzas"."clientes" to "authenticated";

grant select on table "finanzas"."clientes" to "authenticated";

grant trigger on table "finanzas"."clientes" to "authenticated";

grant truncate on table "finanzas"."clientes" to "authenticated";

grant update on table "finanzas"."clientes" to "authenticated";

grant delete on table "finanzas"."clientes" to "service_role";

grant insert on table "finanzas"."clientes" to "service_role";

grant references on table "finanzas"."clientes" to "service_role";

grant select on table "finanzas"."clientes" to "service_role";

grant trigger on table "finanzas"."clientes" to "service_role";

grant truncate on table "finanzas"."clientes" to "service_role";

grant update on table "finanzas"."clientes" to "service_role";

grant delete on table "finanzas"."conceptos_catalogo" to "anon";

grant insert on table "finanzas"."conceptos_catalogo" to "anon";

grant references on table "finanzas"."conceptos_catalogo" to "anon";

grant select on table "finanzas"."conceptos_catalogo" to "anon";

grant trigger on table "finanzas"."conceptos_catalogo" to "anon";

grant truncate on table "finanzas"."conceptos_catalogo" to "anon";

grant update on table "finanzas"."conceptos_catalogo" to "anon";

grant delete on table "finanzas"."conceptos_catalogo" to "authenticated";

grant insert on table "finanzas"."conceptos_catalogo" to "authenticated";

grant references on table "finanzas"."conceptos_catalogo" to "authenticated";

grant select on table "finanzas"."conceptos_catalogo" to "authenticated";

grant trigger on table "finanzas"."conceptos_catalogo" to "authenticated";

grant truncate on table "finanzas"."conceptos_catalogo" to "authenticated";

grant update on table "finanzas"."conceptos_catalogo" to "authenticated";

grant delete on table "finanzas"."conceptos_catalogo" to "service_role";

grant insert on table "finanzas"."conceptos_catalogo" to "service_role";

grant references on table "finanzas"."conceptos_catalogo" to "service_role";

grant select on table "finanzas"."conceptos_catalogo" to "service_role";

grant trigger on table "finanzas"."conceptos_catalogo" to "service_role";

grant truncate on table "finanzas"."conceptos_catalogo" to "service_role";

grant update on table "finanzas"."conceptos_catalogo" to "service_role";

grant delete on table "finanzas"."cotizaciones" to "anon";

grant insert on table "finanzas"."cotizaciones" to "anon";

grant references on table "finanzas"."cotizaciones" to "anon";

grant select on table "finanzas"."cotizaciones" to "anon";

grant trigger on table "finanzas"."cotizaciones" to "anon";

grant truncate on table "finanzas"."cotizaciones" to "anon";

grant update on table "finanzas"."cotizaciones" to "anon";

grant delete on table "finanzas"."cotizaciones" to "authenticated";

grant insert on table "finanzas"."cotizaciones" to "authenticated";

grant references on table "finanzas"."cotizaciones" to "authenticated";

grant select on table "finanzas"."cotizaciones" to "authenticated";

grant trigger on table "finanzas"."cotizaciones" to "authenticated";

grant truncate on table "finanzas"."cotizaciones" to "authenticated";

grant update on table "finanzas"."cotizaciones" to "authenticated";

grant delete on table "finanzas"."cotizaciones" to "service_role";

grant insert on table "finanzas"."cotizaciones" to "service_role";

grant references on table "finanzas"."cotizaciones" to "service_role";

grant select on table "finanzas"."cotizaciones" to "service_role";

grant trigger on table "finanzas"."cotizaciones" to "service_role";

grant truncate on table "finanzas"."cotizaciones" to "service_role";

grant update on table "finanzas"."cotizaciones" to "service_role";

grant delete on table "finanzas"."espacios" to "anon";

grant insert on table "finanzas"."espacios" to "anon";

grant references on table "finanzas"."espacios" to "anon";

grant select on table "finanzas"."espacios" to "anon";

grant trigger on table "finanzas"."espacios" to "anon";

grant truncate on table "finanzas"."espacios" to "anon";

grant update on table "finanzas"."espacios" to "anon";

grant delete on table "finanzas"."espacios" to "authenticated";

grant insert on table "finanzas"."espacios" to "authenticated";

grant references on table "finanzas"."espacios" to "authenticated";

grant select on table "finanzas"."espacios" to "authenticated";

grant trigger on table "finanzas"."espacios" to "authenticated";

grant truncate on table "finanzas"."espacios" to "authenticated";

grant update on table "finanzas"."espacios" to "authenticated";

grant delete on table "finanzas"."espacios" to "service_role";

grant insert on table "finanzas"."espacios" to "service_role";

grant references on table "finanzas"."espacios" to "service_role";

grant select on table "finanzas"."espacios" to "service_role";

grant trigger on table "finanzas"."espacios" to "service_role";

grant truncate on table "finanzas"."espacios" to "service_role";

grant update on table "finanzas"."espacios" to "service_role";

grant delete on table "finanzas"."impuestos" to "anon";

grant insert on table "finanzas"."impuestos" to "anon";

grant references on table "finanzas"."impuestos" to "anon";

grant select on table "finanzas"."impuestos" to "anon";

grant trigger on table "finanzas"."impuestos" to "anon";

grant truncate on table "finanzas"."impuestos" to "anon";

grant update on table "finanzas"."impuestos" to "anon";

grant delete on table "finanzas"."impuestos" to "authenticated";

grant insert on table "finanzas"."impuestos" to "authenticated";

grant references on table "finanzas"."impuestos" to "authenticated";

grant select on table "finanzas"."impuestos" to "authenticated";

grant trigger on table "finanzas"."impuestos" to "authenticated";

grant truncate on table "finanzas"."impuestos" to "authenticated";

grant update on table "finanzas"."impuestos" to "authenticated";

grant delete on table "finanzas"."impuestos" to "service_role";

grant insert on table "finanzas"."impuestos" to "service_role";

grant references on table "finanzas"."impuestos" to "service_role";

grant select on table "finanzas"."impuestos" to "service_role";

grant trigger on table "finanzas"."impuestos" to "service_role";

grant truncate on table "finanzas"."impuestos" to "service_role";

grant update on table "finanzas"."impuestos" to "service_role";

grant delete on table "finanzas_casadepiedra"."clientes" to "anon";

grant insert on table "finanzas_casadepiedra"."clientes" to "anon";

grant references on table "finanzas_casadepiedra"."clientes" to "anon";

grant select on table "finanzas_casadepiedra"."clientes" to "anon";

grant trigger on table "finanzas_casadepiedra"."clientes" to "anon";

grant truncate on table "finanzas_casadepiedra"."clientes" to "anon";

grant update on table "finanzas_casadepiedra"."clientes" to "anon";

grant delete on table "finanzas_casadepiedra"."clientes" to "authenticated";

grant insert on table "finanzas_casadepiedra"."clientes" to "authenticated";

grant references on table "finanzas_casadepiedra"."clientes" to "authenticated";

grant select on table "finanzas_casadepiedra"."clientes" to "authenticated";

grant trigger on table "finanzas_casadepiedra"."clientes" to "authenticated";

grant truncate on table "finanzas_casadepiedra"."clientes" to "authenticated";

grant update on table "finanzas_casadepiedra"."clientes" to "authenticated";

grant delete on table "finanzas_casadepiedra"."clientes" to "service_role";

grant insert on table "finanzas_casadepiedra"."clientes" to "service_role";

grant references on table "finanzas_casadepiedra"."clientes" to "service_role";

grant select on table "finanzas_casadepiedra"."clientes" to "service_role";

grant trigger on table "finanzas_casadepiedra"."clientes" to "service_role";

grant truncate on table "finanzas_casadepiedra"."clientes" to "service_role";

grant update on table "finanzas_casadepiedra"."clientes" to "service_role";

grant delete on table "finanzas_casadepiedra"."conceptos_catalogo" to "anon";

grant insert on table "finanzas_casadepiedra"."conceptos_catalogo" to "anon";

grant references on table "finanzas_casadepiedra"."conceptos_catalogo" to "anon";

grant select on table "finanzas_casadepiedra"."conceptos_catalogo" to "anon";

grant trigger on table "finanzas_casadepiedra"."conceptos_catalogo" to "anon";

grant truncate on table "finanzas_casadepiedra"."conceptos_catalogo" to "anon";

grant update on table "finanzas_casadepiedra"."conceptos_catalogo" to "anon";

grant delete on table "finanzas_casadepiedra"."conceptos_catalogo" to "authenticated";

grant insert on table "finanzas_casadepiedra"."conceptos_catalogo" to "authenticated";

grant references on table "finanzas_casadepiedra"."conceptos_catalogo" to "authenticated";

grant select on table "finanzas_casadepiedra"."conceptos_catalogo" to "authenticated";

grant trigger on table "finanzas_casadepiedra"."conceptos_catalogo" to "authenticated";

grant truncate on table "finanzas_casadepiedra"."conceptos_catalogo" to "authenticated";

grant update on table "finanzas_casadepiedra"."conceptos_catalogo" to "authenticated";

grant delete on table "finanzas_casadepiedra"."conceptos_catalogo" to "service_role";

grant insert on table "finanzas_casadepiedra"."conceptos_catalogo" to "service_role";

grant references on table "finanzas_casadepiedra"."conceptos_catalogo" to "service_role";

grant select on table "finanzas_casadepiedra"."conceptos_catalogo" to "service_role";

grant trigger on table "finanzas_casadepiedra"."conceptos_catalogo" to "service_role";

grant truncate on table "finanzas_casadepiedra"."conceptos_catalogo" to "service_role";

grant update on table "finanzas_casadepiedra"."conceptos_catalogo" to "service_role";

grant delete on table "finanzas_casadepiedra"."cotizaciones" to "anon";

grant insert on table "finanzas_casadepiedra"."cotizaciones" to "anon";

grant references on table "finanzas_casadepiedra"."cotizaciones" to "anon";

grant select on table "finanzas_casadepiedra"."cotizaciones" to "anon";

grant trigger on table "finanzas_casadepiedra"."cotizaciones" to "anon";

grant truncate on table "finanzas_casadepiedra"."cotizaciones" to "anon";

grant update on table "finanzas_casadepiedra"."cotizaciones" to "anon";

grant delete on table "finanzas_casadepiedra"."cotizaciones" to "authenticated";

grant insert on table "finanzas_casadepiedra"."cotizaciones" to "authenticated";

grant references on table "finanzas_casadepiedra"."cotizaciones" to "authenticated";

grant select on table "finanzas_casadepiedra"."cotizaciones" to "authenticated";

grant trigger on table "finanzas_casadepiedra"."cotizaciones" to "authenticated";

grant truncate on table "finanzas_casadepiedra"."cotizaciones" to "authenticated";

grant update on table "finanzas_casadepiedra"."cotizaciones" to "authenticated";

grant delete on table "finanzas_casadepiedra"."cotizaciones" to "service_role";

grant insert on table "finanzas_casadepiedra"."cotizaciones" to "service_role";

grant references on table "finanzas_casadepiedra"."cotizaciones" to "service_role";

grant select on table "finanzas_casadepiedra"."cotizaciones" to "service_role";

grant trigger on table "finanzas_casadepiedra"."cotizaciones" to "service_role";

grant truncate on table "finanzas_casadepiedra"."cotizaciones" to "service_role";

grant update on table "finanzas_casadepiedra"."cotizaciones" to "service_role";

grant delete on table "finanzas_casadepiedra"."espacios" to "anon";

grant insert on table "finanzas_casadepiedra"."espacios" to "anon";

grant references on table "finanzas_casadepiedra"."espacios" to "anon";

grant select on table "finanzas_casadepiedra"."espacios" to "anon";

grant trigger on table "finanzas_casadepiedra"."espacios" to "anon";

grant truncate on table "finanzas_casadepiedra"."espacios" to "anon";

grant update on table "finanzas_casadepiedra"."espacios" to "anon";

grant delete on table "finanzas_casadepiedra"."espacios" to "authenticated";

grant insert on table "finanzas_casadepiedra"."espacios" to "authenticated";

grant references on table "finanzas_casadepiedra"."espacios" to "authenticated";

grant select on table "finanzas_casadepiedra"."espacios" to "authenticated";

grant trigger on table "finanzas_casadepiedra"."espacios" to "authenticated";

grant truncate on table "finanzas_casadepiedra"."espacios" to "authenticated";

grant update on table "finanzas_casadepiedra"."espacios" to "authenticated";

grant delete on table "finanzas_casadepiedra"."espacios" to "service_role";

grant insert on table "finanzas_casadepiedra"."espacios" to "service_role";

grant references on table "finanzas_casadepiedra"."espacios" to "service_role";

grant select on table "finanzas_casadepiedra"."espacios" to "service_role";

grant trigger on table "finanzas_casadepiedra"."espacios" to "service_role";

grant truncate on table "finanzas_casadepiedra"."espacios" to "service_role";

grant update on table "finanzas_casadepiedra"."espacios" to "service_role";

grant delete on table "finanzas_casadepiedra"."impuestos" to "anon";

grant insert on table "finanzas_casadepiedra"."impuestos" to "anon";

grant references on table "finanzas_casadepiedra"."impuestos" to "anon";

grant select on table "finanzas_casadepiedra"."impuestos" to "anon";

grant trigger on table "finanzas_casadepiedra"."impuestos" to "anon";

grant truncate on table "finanzas_casadepiedra"."impuestos" to "anon";

grant update on table "finanzas_casadepiedra"."impuestos" to "anon";

grant delete on table "finanzas_casadepiedra"."impuestos" to "authenticated";

grant insert on table "finanzas_casadepiedra"."impuestos" to "authenticated";

grant references on table "finanzas_casadepiedra"."impuestos" to "authenticated";

grant select on table "finanzas_casadepiedra"."impuestos" to "authenticated";

grant trigger on table "finanzas_casadepiedra"."impuestos" to "authenticated";

grant truncate on table "finanzas_casadepiedra"."impuestos" to "authenticated";

grant update on table "finanzas_casadepiedra"."impuestos" to "authenticated";

grant delete on table "finanzas_casadepiedra"."impuestos" to "service_role";

grant insert on table "finanzas_casadepiedra"."impuestos" to "service_role";

grant references on table "finanzas_casadepiedra"."impuestos" to "service_role";

grant select on table "finanzas_casadepiedra"."impuestos" to "service_role";

grant trigger on table "finanzas_casadepiedra"."impuestos" to "service_role";

grant truncate on table "finanzas_casadepiedra"."impuestos" to "service_role";

grant update on table "finanzas_casadepiedra"."impuestos" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "postgres";

grant insert on table "public"."profiles" to "postgres";

grant references on table "public"."profiles" to "postgres";

grant select on table "public"."profiles" to "postgres";

grant trigger on table "public"."profiles" to "postgres";

grant truncate on table "public"."profiles" to "postgres";

grant update on table "public"."profiles" to "postgres";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";


  create policy "fin_clientes_delete"
  on "finanzas"."clientes"
  as permissive
  for delete
  to authenticated
using (public.can_access_pm());



  create policy "fin_clientes_insert"
  on "finanzas"."clientes"
  as permissive
  for insert
  to authenticated
with check (public.can_access_pm());



  create policy "fin_clientes_select"
  on "finanzas"."clientes"
  as permissive
  for select
  to authenticated
using (public.can_access_pm());



  create policy "fin_clientes_update"
  on "finanzas"."clientes"
  as permissive
  for update
  to authenticated
using (public.can_access_pm())
with check (public.can_access_pm());



  create policy "fin_conceptos_catalogo_admin_delete"
  on "finanzas"."conceptos_catalogo"
  as permissive
  for delete
  to authenticated
using (public.is_admin());



  create policy "fin_conceptos_catalogo_admin_insert"
  on "finanzas"."conceptos_catalogo"
  as permissive
  for insert
  to authenticated
with check (public.is_admin());



  create policy "fin_conceptos_catalogo_admin_update"
  on "finanzas"."conceptos_catalogo"
  as permissive
  for update
  to authenticated
using (public.is_admin())
with check (public.is_admin());



  create policy "fin_conceptos_catalogo_select"
  on "finanzas"."conceptos_catalogo"
  as permissive
  for select
  to authenticated
using (public.can_access_pm());



  create policy "fin_cotizaciones_delete"
  on "finanzas"."cotizaciones"
  as permissive
  for delete
  to authenticated
using (public.can_access_pm());



  create policy "fin_cotizaciones_insert"
  on "finanzas"."cotizaciones"
  as permissive
  for insert
  to authenticated
with check (public.can_access_pm());



  create policy "fin_cotizaciones_select"
  on "finanzas"."cotizaciones"
  as permissive
  for select
  to authenticated
using (public.can_access_pm());



  create policy "fin_cotizaciones_update"
  on "finanzas"."cotizaciones"
  as permissive
  for update
  to authenticated
using (public.can_access_pm())
with check (public.can_access_pm());



  create policy "fin_espacios_delete"
  on "finanzas"."espacios"
  as permissive
  for delete
  to authenticated
using (public.can_access_pm());



  create policy "fin_espacios_insert"
  on "finanzas"."espacios"
  as permissive
  for insert
  to authenticated
with check (public.can_access_pm());



  create policy "fin_espacios_select"
  on "finanzas"."espacios"
  as permissive
  for select
  to authenticated
using (public.can_access_pm());



  create policy "fin_espacios_update"
  on "finanzas"."espacios"
  as permissive
  for update
  to authenticated
using (public.can_access_pm())
with check (public.can_access_pm());



  create policy "fin_impuestos_admin_delete"
  on "finanzas"."impuestos"
  as permissive
  for delete
  to authenticated
using (public.is_admin());



  create policy "fin_impuestos_admin_insert"
  on "finanzas"."impuestos"
  as permissive
  for insert
  to authenticated
with check (public.is_admin());



  create policy "fin_impuestos_admin_update"
  on "finanzas"."impuestos"
  as permissive
  for update
  to authenticated
using (public.is_admin())
with check (public.is_admin());



  create policy "fin_impuestos_select"
  on "finanzas"."impuestos"
  as permissive
  for select
  to authenticated
using (public.can_access_pm());



  create policy "cp_clientes_delete"
  on "finanzas_casadepiedra"."clientes"
  as permissive
  for delete
  to authenticated
using (public.can_access_cp());



  create policy "cp_clientes_insert"
  on "finanzas_casadepiedra"."clientes"
  as permissive
  for insert
  to authenticated
with check (public.can_access_cp());



  create policy "cp_clientes_select"
  on "finanzas_casadepiedra"."clientes"
  as permissive
  for select
  to authenticated
using (public.can_access_cp());



  create policy "cp_clientes_update"
  on "finanzas_casadepiedra"."clientes"
  as permissive
  for update
  to authenticated
using (public.can_access_cp())
with check (public.can_access_cp());



  create policy "cp_conceptos_catalogo_admin_delete"
  on "finanzas_casadepiedra"."conceptos_catalogo"
  as permissive
  for delete
  to authenticated
using (public.is_admin());



  create policy "cp_conceptos_catalogo_admin_insert"
  on "finanzas_casadepiedra"."conceptos_catalogo"
  as permissive
  for insert
  to authenticated
with check (public.is_admin());



  create policy "cp_conceptos_catalogo_admin_update"
  on "finanzas_casadepiedra"."conceptos_catalogo"
  as permissive
  for update
  to authenticated
using (public.is_admin())
with check (public.is_admin());



  create policy "cp_conceptos_catalogo_select"
  on "finanzas_casadepiedra"."conceptos_catalogo"
  as permissive
  for select
  to authenticated
using (public.can_access_cp());



  create policy "cp_cotizaciones_delete"
  on "finanzas_casadepiedra"."cotizaciones"
  as permissive
  for delete
  to authenticated
using (public.can_access_cp());



  create policy "cp_cotizaciones_insert"
  on "finanzas_casadepiedra"."cotizaciones"
  as permissive
  for insert
  to authenticated
with check (public.can_access_cp());



  create policy "cp_cotizaciones_select"
  on "finanzas_casadepiedra"."cotizaciones"
  as permissive
  for select
  to authenticated
using (public.can_access_cp());



  create policy "cp_cotizaciones_update"
  on "finanzas_casadepiedra"."cotizaciones"
  as permissive
  for update
  to authenticated
using (public.can_access_cp())
with check (public.can_access_cp());



  create policy "cp_espacios_delete"
  on "finanzas_casadepiedra"."espacios"
  as permissive
  for delete
  to authenticated
using (public.can_access_cp());



  create policy "cp_espacios_insert"
  on "finanzas_casadepiedra"."espacios"
  as permissive
  for insert
  to authenticated
with check (public.can_access_cp());



  create policy "cp_espacios_select"
  on "finanzas_casadepiedra"."espacios"
  as permissive
  for select
  to authenticated
using (public.can_access_cp());



  create policy "cp_espacios_update"
  on "finanzas_casadepiedra"."espacios"
  as permissive
  for update
  to authenticated
using (public.can_access_cp())
with check (public.can_access_cp());



  create policy "cp_impuestos_admin_delete"
  on "finanzas_casadepiedra"."impuestos"
  as permissive
  for delete
  to authenticated
using (public.is_admin());



  create policy "cp_impuestos_admin_insert"
  on "finanzas_casadepiedra"."impuestos"
  as permissive
  for insert
  to authenticated
with check (public.is_admin());



  create policy "cp_impuestos_admin_update"
  on "finanzas_casadepiedra"."impuestos"
  as permissive
  for update
  to authenticated
using (public.is_admin())
with check (public.is_admin());



  create policy "cp_impuestos_select"
  on "finanzas_casadepiedra"."impuestos"
  as permissive
  for select
  to authenticated
using (public.can_access_cp());



  create policy "profiles_insert_own"
  on "public"."profiles"
  as permissive
  for insert
  to authenticated
with check (((id = ( SELECT auth.uid() AS uid)) OR public.is_admin()));



  create policy "profiles_select_self_or_admin"
  on "public"."profiles"
  as permissive
  for select
  to authenticated
using (((id = ( SELECT auth.uid() AS uid)) OR public.is_admin()));



  create policy "profiles_update_self_or_admin"
  on "public"."profiles"
  as permissive
  for update
  to authenticated
using (((id = ( SELECT auth.uid() AS uid)) OR public.is_admin()))
with check (((id = ( SELECT auth.uid() AS uid)) OR public.is_admin()));


CREATE TRIGGER trg_finanzas_clientes_updated_at BEFORE UPDATE ON finanzas.clientes FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_fcdp_clientes_updated_at BEFORE UPDATE ON finanzas_casadepiedra.clientes FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER profiles_set_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

CREATE TRIGGER on_auth_user_created_profile AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user_profile();


  create policy "Authenticated Delete Espacios"
  on "storage"."objects"
  as permissive
  for delete
  to authenticated
using ((bucket_id = 'Espacios'::text));



  create policy "Authenticated Insert Espacios"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check ((bucket_id = 'Espacios'::text));



  create policy "Authenticated Update Espacios"
  on "storage"."objects"
  as permissive
  for update
  to authenticated
using ((bucket_id = 'Espacios'::text));



  create policy "Public Access Espacios"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'Espacios'::text));



  create policy "cp_docs_delete"
  on "storage"."objects"
  as permissive
  for delete
  to authenticated
using (((bucket_id = 'documentos-cp'::text) AND (public.is_admin() OR (owner = auth.uid()))));



  create policy "cp_docs_insert"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check (((bucket_id = 'documentos-cp'::text) AND public.can_access_cp()));



  create policy "cp_docs_select"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using (((bucket_id = 'documentos-cp'::text) AND public.can_access_cp()));



  create policy "cp_docs_update"
  on "storage"."objects"
  as permissive
  for update
  to authenticated
using (((bucket_id = 'documentos-cp'::text) AND (public.is_admin() OR (owner = auth.uid()))))
with check (((bucket_id = 'documentos-cp'::text) AND (public.is_admin() OR (owner = auth.uid()))));



  create policy "pm_docs_delete"
  on "storage"."objects"
  as permissive
  for delete
  to authenticated
using (((bucket_id = 'documentos'::text) AND (public.is_admin() OR (owner = auth.uid()))));



  create policy "pm_docs_insert"
  on "storage"."objects"
  as permissive
  for insert
  to authenticated
with check (((bucket_id = 'documentos'::text) AND public.can_access_pm()));



  create policy "pm_docs_select"
  on "storage"."objects"
  as permissive
  for select
  to authenticated
using (((bucket_id = 'documentos'::text) AND public.can_access_pm()));



  create policy "pm_docs_update"
  on "storage"."objects"
  as permissive
  for update
  to authenticated
using (((bucket_id = 'documentos'::text) AND (public.is_admin() OR (owner = auth.uid()))))
with check (((bucket_id = 'documentos'::text) AND (public.is_admin() OR (owner = auth.uid()))));



